# Generated by Django 5.1.4 on 2025-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="assessment",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
